### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by EC2EZ4RD** [crowdAI/marlo-single-agent-starter-kit#3]
Because I used `chainer` and `chainerrl`, so `cupy` is needed.
But when I built image, it showed me that

    **************************************************
    *** WARNING: nvcc not in path.
    *** WARNING: Please set path to nvcc.
    **************************************************
    
    -------- Configuring Module: cuda --------
    command 'gcc' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: []
      Library directories: ['/usr/local/cuda/lib64']
      nvcc command       : (not found)
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cflxwwqf/cupy/setup.py", line 64, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-install-cflxwwqf/cupy/cupy_setup_build.py", line 583, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-install-cflxwwqf/cupy/cupy_setup_build.py", line 379, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.

So, could you please help to solve it?
Many thanks

**Comment by EC2EZ4RD** [comment]
And I found this docker used cuda:9.0-runtime-ubuntu16.04 as base docker which is without `nvcc`.
So I tried add `apt.txt` with:

apt-utils
libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0

But it still did not work with warning: "debconf: delaying package configuration, since apt-utils is not installed".

**Comment by spMohanty** [comment]
Hi,

You can also include a Dockerfile at the root of your repository, and it
will be used instead to build the image.

Cheers,
Mohanty

**Comment by EC2EZ4RD** [comment]
Yeah, I am writing a new dockerfile and having a try.
